import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createStudioServer} from '../studio/server.js';
const unit={title:'A local slope',text:'The slope at x equals one is two.',kind:'grounded',sourceIds:['source.local'],focusId:'p1.derivative',scene:{tangent:true,secant:false,comparison:false},note:null,claims:[{key:'slope',value:2}],reviewReason:null,functionCode:null};
async function setup(t,speechImpl){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'studio-speech-http-'));const app=createStudioServer({port:0,dataDir:dir,keyConfigured:true,speechImpl,generateImpl:async()=>({unit,metadata:{}})});await app.listen();const url=`http://127.0.0.1:${app.server.address().port}`;t.after(()=>{app.close();fs.rmSync(dir,{recursive:true,force:true});});const session=await(await fetch(url+'/api/session')).json();const post=(route,input)=>fetch(url+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectionId:session.connectionId,...input})});return{app,url,session,post};}
test('native speech receives only server-prepared text, remains ready until actual playback, and rejects stale identity',async t=>{let seen;const{app,session,post}=await setup(t,{available:true,synthesize:async text=>{seen=text;return Buffer.from('RIFF_test_WAVE');}});assert.equal(session.config.nativeSpeech,true);const ready=await(await post('/api/control',{action:'start'})).json();const r=await post('/api/speech',{stepId:ready.step.id,text:'client override must not be used'});assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/audio\/wav/);assert.equal(seen,ready.step.text);assert.equal(app.core.audioAnchor.phase,'ready');assert.equal(app.core.state.delivery,'idle');await post('/api/control',{action:'parameter',a:3});assert.equal((await post('/api/speech',{stepId:ready.step.id})).status,409);});
test('answer speech is unavailable before display ACK; afterward it uses the accepted answer only',async t=>{let calls=0,seen;const{app,session,post}=await setup(t,{available:true,synthesize:async text=>{calls++;seen=text;return Buffer.from('RIFF_test_WAVE');}});const s=session.state;const q=await(await post('/api/ask',{question:'Show the local slope.',clientTurnId:'speech-test',revision:s.revision,viewEpoch:s.viewEpoch,pageId:s.pageId,selectedId:s.selectedId})).json();assert.equal((await post('/api/speech',{turnId:q.turnId})).status,409);assert.equal(calls,0);const ack=await post('/api/ack',{turnId:q.turnId,clientTurnId:'speech-test',revision:app.core.state.revision,renderedMs:50});assert.equal(ack.status,200);assert.equal((await post('/api/speech',{turnId:q.turnId,text:'not this'})).status,200);assert.equal(seen,unit.text);assert.equal(calls,1);});
test('page changes during synthesis discard the returned WAV without authorizing playback',async t=>{let finish,entered;const running=new Promise(resolve=>entered=resolve);const{app,post}=await setup(t,{available:true,synthesize:()=>{entered();return new Promise(resolve=>finish=resolve);}});const ready=await(await post('/api/control',{action:'start'})).json();const pending=post('/api/speech',{stepId:ready.step.id});await running;await post('/api/control',{action:'page',pageId:'p2'});finish(Buffer.from('RIFF_test_WAVE'));const res=await pending;assert.equal(res.status,409);assert.equal((await res.json()).error.code,'STALE_AUDIO');assert.equal(app.core.audioAnchor,null);});
